# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'

        sftp:
            sftp:
                options:
                    host: ftp.g4npvplus.net
                    username: pvpluy_11
                    password: hEgxVX579NtHTMZ1
                    port: 22
                    root: ./
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter

        sftp:
            adapter: sftp
