# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'

        sftp:
            sftp:
                options:
                    host: serv49313224-prod-app01.secure-node.de
                    username: f6
                    password: '%env(sftp_password)%'
                    port: 10422
                    root: ./
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter

        sftp:
            adapter: sftp
