# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    totp:
        enabled: true
        issuer: 'PVplus 4.0'
        template: 'login/2fa_form.html.twig'

    email:
        enabled: true
        digits: 6
        sender_email: no-reply@g4npvplus.de
        sender_name: pvplus  # Optional
        template: 'login/2fa_form.html.twig'
