twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        'public/images': images
        'public/scss/email': styles
        'public/scss/': pdf

    form_themes:
        - 'form/foundation_6_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'


when@test:
    twig:
        strict_variables: true

